export const appleMenuItems = [
    { label: 'About This Mac' },
    { type: 'divider' },
    { label: 'System Settings...', badge: '1 update' },
    { label: 'App Store...', badge: '5 updates' },
    { type: 'divider' },
    { label: 'Recent Items', arrow: true },
    { type: 'divider' },
    { label: 'Force Quit...', shortcut: '⌥⌘⎋' },
    { type: 'divider' },
    { label: 'Sleep' },
    { label: 'Restart...' },
    { label: 'Shut Down...' },
    { type: 'divider' },
    { label: 'Lock Screen', shortcut: '⌃⌘Q' },
    { label: 'Log Out zedithx...', shortcut: '⇧⌘Q' },
];

export const iTermMenuItems = [
    { label: 'About iTerm2' },
    { label: 'Show Tip of the Day' },
    { type: 'divider' },
    { label: 'Check for Updates...' },
    { type: 'divider' },
    { label: 'Toggle Debug Logging' },
    { label: 'Copy Performance Stats' },
    { type: 'divider' },
    { label: 'Settings...', shortcut: '⌘,' },
    { type: 'divider' },
    { label: 'Services', arrow: true },
    { type: 'divider' },
    { label: 'Hide iTerm2', shortcut: '⌘H' },
    { label: 'Hide Others', shortcut: '⌥⌘H' },
    { type: 'disabled', label: 'Show All' },
    { type: 'divider' },
    { label: 'Secure Keyboard Entry', shortcut: '⌥⌘S' },
    { type: 'divider' },
    { label: 'Make iTerm2 Default Term', shortcut: '⌃⇧⌘\\' },
    { label: 'Install Shell Integration' },
    { type: 'divider' },
    { label: 'Quit iTerm2', shortcut: '⌘Q' },
];

export const fileMenuItems = [
    { label: 'New Text File', shortcut: '⌘N' },
    { label: 'New Window', shortcut: '⇧⌘N' },
    { label: 'New Window with Profile', arrow: true },
    { type: 'divider' },
    { label: 'Open...', shortcut: '⌘O' },
    { label: 'Open Folder...' },
    { label: 'Open Workspace from File...' },
    { label: 'Open Recent', arrow: true },
    { type: 'divider' },
    { label: 'Add Folder to Workspace...' },
    { label: 'Save Workspace As...' },
    { label: 'Duplicate Workspace' },
    { type: 'divider' },
    { label: 'Save', shortcut: '⌘S' },
    { label: 'Save As...', shortcut: '⇧⌘S' },
    { type: 'disabled', label: 'Save All', shortcut: '⌥⌘S' },
    { type: 'divider' },
    { label: 'Share', arrow: true },
    { type: 'divider' },
    { label: 'Auto Save', checked: true },
    { type: 'divider' },
    { label: 'Revert File' },
    { label: 'Close Editor', shortcut: '⌘W' },
    { label: 'Close Folder', shortcut: '⌘K F' },
    { label: 'Close Window', shortcut: '⇧⌘W' },
];

export const editMenuItems = [
    { label: 'Undo', shortcut: '⌘Z' },
    { label: 'Redo', shortcut: '⇧⌘Z' },
    { type: 'divider' },
    { label: 'Cut', shortcut: '⌘X' },
    { label: 'Copy', shortcut: '⌘C' },
    { label: 'Paste', shortcut: '⌘V' },
    { type: 'divider' },
    { label: 'Find', shortcut: '⌘F' },
    { label: 'Replace', shortcut: '⌥⌘F' },
    { type: 'divider' },
    { label: 'Find in Files', shortcut: '⇧⌘F' },
    { label: 'Replace in Files', shortcut: '⇧⌘H' },
    { type: 'divider' },
    { label: 'Toggle Line Comment', shortcut: '⌘/' },
    { label: 'Toggle Block Comment', shortcut: '⌥⇧A' },
    { label: 'Emmet: Expand Abbreviation', shortcut: '⇥' },
    { type: 'divider' },
    { label: 'Writing Tools', arrow: true },
    { label: 'AutoFill', arrow: true },
    { label: 'Start Dictation...' },
    { label: 'Emoji & Symbols', shortcut: '🌐E' },
];

export const viewMenuItems = [
    { label: 'Show Sidebar', shortcut: '⌘B' },
    { label: 'Hide Sidebar', shortcut: '⌘B' },
    { type: 'divider' },
    { label: 'Appearance', arrow: true },
    { label: 'Editor Layout', arrow: true },
    { type: 'divider' },
    { label: 'Zoom In', shortcut: '⌘+' },
    { label: 'Zoom Out', shortcut: '⌘-' },
    { label: 'Reset Zoom', shortcut: '⌘0' },
];

export const goMenuItems = [
    { label: 'Back', shortcut: '⌘[' },
    { label: 'Forward', shortcut: '⌘]' },
    { type: 'divider' },
    { label: 'Go to File...', shortcut: '⌘P' },
    { label: 'Go to Symbol in File...', shortcut: '⌘⇧O' },
    { label: 'Go to Symbol in Workspace...', shortcut: '⌘T' },
    { type: 'divider' },
    { label: 'Go to Line/Column...', shortcut: '⌘G' },
    { label: 'Go to Definition', shortcut: 'F12' },
    { label: 'Go to Declaration', shortcut: '⌘F12' },
];

export const windowMenuItems = [
    { label: 'Minimize', shortcut: '⌘M' },
    { label: 'Zoom' },
    { type: 'divider' },
    { label: 'Move Tab to New Window' },
    { label: 'Merge All Windows' },
    { type: 'divider' },
    { type: 'disabled', label: '1 Terminal — zsh' },
    { type: 'divider' },
    { label: 'Bring All to Front' },
];

export const helpMenuItems = [
    { label: 'Get Started' },
    { label: 'Documentation' },
    { label: 'Release Notes' },
    { type: 'divider' },
    { label: 'Keyboard Shortcuts Reference' },
    { label: 'Video Tutorials' },
    { type: 'divider' },
    { label: 'Tips and Tricks' },
    { type: 'divider' },
    { label: 'Report Issue' },
    { label: 'Feature Request' },
    { type: 'divider' },
    { label: 'Community' },
];
