// Public project dossiers. Facts are drawn from the existing portfolio; reasoning
// reconstructed for this view and future work are labelled separately.
export const EVIDENCE_FILE_IDS = ['demo', 'architecture', 'decisions', 'results', 'change'];

const fileNames = {
  demo: 'Demo', architecture: 'Architecture', decisions: 'Decisions',
  results: 'Results', change: 'What I’d change',
};

function dossier(config) {
  const { demo, architecture, decisions, results, change, ...project } = config;
  return {
    ...project,
    tags: [...new Set([project.category, ...project.skills, ...(project.tags || [])])],
    files: [
      { id: 'demo', title: fileNames.demo, kind: 'Project evidence', summary: demo.summary, sections: demo.sections || [], media: demo.media || [], links: demo.links || [] },
      { id: 'architecture', title: fileNames.architecture, kind: 'Architecture reconstruction', summary: architecture.summary, sections: architecture.sections || [], diagram: architecture.diagram, media: architecture.media || [], links: architecture.links || [] },
      { id: 'decisions', title: fileNames.decisions, kind: 'Tradeoff analysis', summary: decisions.summary, sections: decisions.sections, links: [] },
      { id: 'results', title: fileNames.results, kind: 'Recorded results', summary: results.summary, sections: results.sections, media: results.media || [], links: results.links || [] },
      { id: 'change', title: fileNames.change, kind: 'Future proposal', summary: change.summary, sections: change.sections, links: [] },
    ],
  };
}

const section = (title, body) => ({ title, body });
const image = (src, alt, caption) => ({ type: 'image', src, alt, caption });
const link = (label, href) => ({ label, href });

export const projectEvidence = [
  dossier({
    id: 'tangled', sourceId: 11, title: 'Tangled', category: 'Featured Project',
    skills: ['Expo', 'Python', 'AWS', 'WebSocket Gateway', 'Lambda', 'DynamoDB', 'Terraform', 'Sentry', 'Cloud architecture', 'SRE'],
    summary: 'A live social product: from interest discovery to real-time conversations and production operations.',
    demo: { summary: 'Co-founded a social platform available on the App Store with 4k+ users. The existing portfolio records real-time chat, interest-based discovery, and group planning.', media: [image('/projects/tangled/TangledMockup.jpeg', 'Tangled mobile app screens', 'Existing Tangled product mockup.')], links: [link('Tangled website', 'https://www.tangledsocial.com')] },
    architecture: { summary: 'A simplified reconstruction from the technologies described in the portfolio, rather than a production topology export.', diagram: [section('Mobile client', 'Expo app · discovery, groups, chat'), section('Realtime edge', 'AWS WebSocket Gateway'), section('Message handling', 'Python / AWS Lambda'), section('Persistence', 'DynamoDB')], sections: [section('Infrastructure and operation', 'Terraform provisions infrastructure. Sentry and end-to-end monitoring support the live product. The portfolio also records ECS rolling deployments; this diagram focuses on the chat path and does not imply that every workload runs on Lambda.')] },
    decisions: { summary: 'The recorded implementation uses managed cloud services and infrastructure as code. These tradeoffs are an analysis of that implementation, not a recovered historical decision log.', sections: [section('Managed realtime components', 'WebSocket Gateway and Lambda avoid operating every part of the connection infrastructure. Connection state, message delivery, retries, and service limits still need deliberate handling.'), section('Reproducible infrastructure', 'Terraform makes infrastructure changes inspectable and repeatable. State management and safe rollout remain operational responsibilities.'), section('Operating a social product', 'A successful request is not necessarily a delivered conversation. Useful reliability signals should follow the user journey through connection, message handling, and persistence.')] },
    results: { summary: 'Live App Store product with 4k+ users, as recorded in the existing portfolio.', sections: [section('My contribution', 'Co-founded the product and built the majority of the codebase, including realtime chat and cloud infrastructure.'), section('Evidence boundary', 'No uptime percentage, incident recovery time, or production latency distribution is supplied. Those metrics are not presented as measured achievements here.')] },
    change: { summary: 'A proposed next iteration: measure whether people can complete the connection and conversation journey.', sections: [section('User-facing reliability', 'Define delivery and conversation-completion signals, then connect errors to those journeys rather than relying only on infrastructure health.'), section('Failure rehearsal', 'Exercise reconnects, duplicate delivery, and throttling in a sandbox. Review retry budgets and observable recovery before changing production behavior.')] },
  }),
  dossier({
    id: 'night-fiesta-rfid', sourceId: 4, title: 'Night Fiesta RFID System', category: 'Student Government',
    skills: ['RFID', 'Hardware', 'Python', 'Django', 'PostgreSQL', 'Event operations', 'Backend', 'Frontend'],
    summary: 'An end-to-end carnival system joining physical wristbands, booth operations, and a software backend.',
    demo: { summary: 'Led an RFID-based game carnival implementation, including custom wristband sourcing, RFID readers, and supporting software. The project catalogue also records contactless check-in and attendance tracking.', media: [image('/projects/nightfiestarfid/rfid.png', 'Night Fiesta RFID project image', 'Existing project image. A live reader or scan recording is not attached.')], sections: [section('Hardware and logistics', 'Custom RFID bands were sourced from a supplier in China. Readers and event software formed one operational system rather than separate hardware and web projects.'), section('At the booth', 'The About Me page records backend services managing 60 game booths and 600 visitors. The résumé records a real-time leaderboard, JWT authentication, and role-based API access. The precise scan protocol and reader model are not supplied.')] },
    architecture: { summary: 'A reconstruction that connects the documented hardware and software pieces. Arrows describe their responsibilities; exact transport, reader model, deployment topology, and schema are not supplied.', diagram: [section('Participant', 'Custom RFID wristband · physical identity token'), section('Booth', 'RFID reader + operator workflow'), section('Application', 'Python / Django · JWT and role-based API access'), section('Records and feedback', 'PostgreSQL / real-time leaderboard')], sections: [section('The physical-to-digital boundary', 'The reader produces an identifier; the application associates that identifier with event records. The résumé documents a leaderboard and authenticated API access; this reconstruction does not invent their specific data model.'), section('Operating the event', 'Band distribution, reader placement, staff instructions, and exception handling affect whether a technically correct backend is usable during a carnival. These are operational considerations, not claims that a particular fallback was implemented.')] },
    decisions: { summary: 'The documented choice was to own the hardware-to-software implementation. This analysis explains the questions that choice raises without inventing a historical rationale.', sections: [section('Contactless interaction', 'RFID can make the physical interaction simple. Duplicate reads, band assignment mistakes, and reader connectivity must still be handled by the application and staff workflow.'), section('One end-to-end workflow', 'Hardware sourcing and deployment need to agree with backend identity handling and booth feedback. A device arriving successfully does not prove that a complete participant workflow works.'), section('Operational correctness', 'A reliable booth interaction needs clear accepted/rejected/pending states and an auditable record. The supplied portfolio does not establish the actual deduplication or offline strategy.')] },
    results: { summary: 'Recorded contribution: led the RFID carnival system end-to-end, covering bands, readers, backend, and frontend. The About Me page records 60 game booths and 600 visitors.', sections: [section('What is evidenced', 'The portfolio records the delivered RFID system and event scale. The résumé records a Django Game Booth Carnival System with a real-time leaderboard, JWT authentication, and role-based API access.'), section('What is not measured here', 'The booth and visitor counts describe scope. No scan-throughput, queue-reduction, or availability measurement is supplied; those outcomes are not inferred from event size.')] },
    change: { summary: 'A proposed event-readiness pass focused on duplicate scans, uncertain connectivity, and human recovery.', sections: [section('Replay-safe scans', 'Give a scan an identity and make repeat handling explicit. Show a useful booth result rather than making an operator infer whether a request succeeded.'), section('Connectivity rehearsal', 'Test reader disconnects and delayed responses. If offline buffering is appropriate, expose pending synchronization and reconcile records instead of silently treating queued scans as committed.'), section('Booth runbook', 'Create a short staff guide for replacement bands, device checks, and escalation. Rehearse the whole wristband-to-record path before the event.')] },
  }),
  dossier({
    id: 'plant-pulse', sourceId: 2, title: 'Plant Pulse', category: 'School Projects',
    skills: ['Python', 'Next.js', 'TypeScript', 'AWS', 'CDK', 'IoT Core', 'Lambda', 'DynamoDB', 'EventBridge', 'SNS', 'SQS', 'S3', 'SageMaker', 'Cloud Computing', 'IoT', 'Machine learning'],
    summary: 'IoT plant monitoring that links environmental measurements, cloud data, and disease detection.',
    demo: { summary: 'An intelligent plant-monitoring project with environmental data, AI-powered disease detection, autonomous healing functions, and alerts.', media: [image('/projects/plantpulse/plantpulse.png', 'Plant Pulse project image', 'Existing Plant Pulse project media.')], links: [link('Source repository', 'https://github.com/zedithx/Cloud-Iot-Infra')] },
    architecture: { summary: 'A simplified reconstruction from the project description and résumé, accompanied by the original cloud architecture artifact.', diagram: [section('Plant environment', 'IoT measurements / AWS IoT Core'), section('Processing', 'Python / Lambda / SageMaker · data and predictions'), section('Cloud workflows', 'DynamoDB / EventBridge / SNS / SQS / S3'), section('User view', 'Next.js / TypeScript · status and alerts')], sections: [section('Infrastructure as code', 'The résumé records AWS CDK for this project. The simplified diagram groups responsibilities; consult the original artifact for the detailed architecture.')], media: [image('/projects/plantpulse/Cloud Architecture.png', 'Original Plant Pulse cloud architecture', 'Original architecture artifact from the project page.')] },
    decisions: { summary: 'The recorded stack combines hardware, cloud storage, and a web interface. These are current tradeoff observations about that design.', sections: [section('More than a dashboard', 'A current sensor reading, a model prediction, and a physical intervention carry different levels of uncertainty. An interface should distinguish them.'), section('Cloud-backed history', 'Stored observations enable trends and investigation. Sensor freshness, timestamps, and missing samples matter as much as the latest displayed value.')] },
    results: { summary: 'Recorded as a Top 3 school project in the portfolio.', sections: [section('Delivered scope', 'Environmental monitoring, disease detection, autonomous healing functions, and proactive alerts are described in the original project page.'), section('Measurement boundary', 'No model accuracy, long-term plant outcome, or production reliability measurement is supplied in this dossier.')] },
    change: { summary: 'A proposed iteration that exposes sensor freshness and model confidence.', sections: [section('Trustworthy readings', 'Display last-seen timestamps and missing-data states. Alert on sensor silence separately from an unhealthy plant.'), section('Safer intervention', 'Document confidence and guardrails for healing actions. Review predictions against held-out observations before claiming effectiveness.')] },
  }),
  dossier({
    id: 'bulkify', sourceId: 1, title: 'Bulkify', category: 'School Projects',
    skills: ['Java', 'Android', 'Firebase', 'Stripe', 'Stream.io', 'Algolia', 'Hardware'],
    summary: 'Group purchasing with threshold-based payments, conversations, and a physical pickup locker.',
    demo: { summary: 'An Android app built in Java for group purchases, centralized delivery, and payment processing. The original project page includes a recorded demo.', media: [image('/projects/bulkify/bulkify.png', 'Bulkify application image', 'Existing project image.')], links: [link('Watch recorded demo', 'https://www.youtube.com/watch?v=ccrcRkjByKM'), link('Source repository', 'https://github.com/zedithx/JavaAndroidFE')] },
    architecture: { summary: 'A reconstruction of the documented purchase and pickup flow; it does not specify undocumented service boundaries.', diagram: [section('Buyer and seller', 'Java Android application'), section('Coordination', 'Firebase · search and Stream.io communication'), section('Purchase threshold', 'Stripe payment integration'), section('Pickup', 'QR-based hardware locker workflow')], media: [image('/projects/bulkify/bulkify_locker.png', 'Bulkify hardware locker', 'Hardware locker artifact from the original project.')] },
    decisions: { summary: 'The existing project records threshold-based purchasing, Stripe integration, messaging, and QR pickup. This is an analysis of the resulting tradeoffs.', sections: [section('Commit after a threshold', 'Withholding payment until an order reaches its minimum protects the group-purchase flow. Payment status and order status still need to agree when a request fails.'), section('Physical pickup', 'A locker connects a digital order to a physical handoff. Access assignment, expired pickup credentials, and support paths become part of correctness.')] },
    results: { summary: 'Third place out of 30 teams, judged by Singtel engineers, as recorded in the original project page.', sections: [section('Delivery constraint', 'The Android application was developed during a six-week module project and demonstrated in person.'), section('Evidence boundary', 'The placement is a project result. No real-world cost savings, payment volume, or production adoption is claimed here.')], media: [image('/projects/bulkify/bulkify_poster.png', 'Bulkify project poster', 'Existing project poster.')] },
    change: { summary: 'A proposed next pass on payment transitions and pickup exception handling.', sections: [section('Failure-state tests', 'Exercise a threshold being reached during payment failure, cancelled orders, and duplicate callbacks. Make the user-visible state explicit.'), section('Locker recovery', 'Document manual support when a locker fails to open, and audit credential assignment and invalidation.')] },
  }),
  dossier({
    id: 'enable-id', sourceId: 3, title: 'EnableID', category: 'School Projects',
    skills: ['Next.js', 'Ruby on Rails', 'PostgreSQL', 'RSpec', 'Cypress', 'Tesseract', 'Google Dialogflow', 'Google Gemini LLM', 'AWS Rekognition'],
    summary: 'A refugee identification and support platform with document verification workflows.',
    demo: { summary: 'A platform for refugee identification and support, combining identity management and document verification.', media: [image('/projects/enableid/ocr.png', 'EnableID document recognition interface', 'Existing document recognition project image.')], links: [link('Source repository', 'https://github.com/Service-Design-Studio/1d-final-project-summer-2024-SDS-2024-Team-14')] },
    architecture: { summary: 'A reconstruction from the published stack, grouping components by responsibility without asserting undocumented data flows.', diagram: [section('User interface', 'Next.js'), section('Application', 'Ruby on Rails'), section('Records', 'PostgreSQL'), section('Assistance and extraction', 'OCR / Dialogflow / Gemini / Rekognition')], sections: [section('Validation layers', 'RSpec and Cypress appear in the recorded stack. A verified backend state and a working user workflow need complementary checks.')] },
    decisions: { summary: 'The project combines application records with automated document assistance. These are analytical tradeoffs, not documented historical decisions.', sections: [section('Extraction versus identity', 'OCR output helps process a document; it does not establish that an identity is valid. Uncertain matches need a clear review path.'), section('User trust', 'A support workflow must explain missing or rejected information without exposing unnecessary identity details. Data minimization and access decisions deserve explicit design.')] },
    results: { summary: 'Recorded as a Top 2 school project in the portfolio.', sections: [section('Delivered scope', 'The portfolio describes identity management, support services, and document verification.'), section('Evidence boundary', 'No field deployment count, recognition accuracy, or security audit result is supplied.')] },
    change: { summary: 'A proposed review of uncertain document matches and sensitive-data handling.', sections: [section('Human review', 'Expose extraction confidence and route uncertain cases to review. Test accessibility and failure messages with realistic document quality.'), section('Data lifecycle', 'Document retention, deletion, and access boundaries before expanding the identity workflow.')] },
  }),
  dossier({
    id: 'monitoring-suite', sourceId: 5, title: 'Monitoring Suite', category: 'DevOps Projects',
    skills: ['Go', 'Grafana', 'Prometheus', 'Azure Cloud', 'Docker Compose', 'CI/CD', 'Observability'],
    summary: 'Monitoring and deployment tooling linking a Go service, container workflows, and cloud operations.',
    demo: { summary: 'A DevOps monitoring and CI/CD system built on Go with Docker optimization and Azure Cloud deployment.', media: [image('/projects/monitoring-suite/cicd.png', 'Monitoring Suite CI/CD project diagram', 'Existing monitoring and CI/CD artifact.')] },
    architecture: { summary: 'A reconstruction grouping the recorded technologies into deployment and observation responsibilities.', diagram: [section('Application', 'Go service'), section('Packaging', 'Docker / Docker Compose'), section('Deployment', 'Azure Cloud · CI/CD workflow'), section('Observation', 'Prometheus metrics / Grafana views')] },
    decisions: { summary: 'Containers and monitoring are recorded implementation choices; the reasoning below is a present-day analysis.', sections: [section('Repeatable environments', 'Containerized workflows reduce environment drift but still require explicit configuration and dependency handling.'), section('Signals that guide action', 'A dashboard becomes useful when a signal leads to an investigation or operation. A graph alone does not establish a reliability improvement.')] },
    results: { summary: 'The portfolio records the monitoring and CI/CD implementation with Go, Docker, and Azure.', sections: [section('Available artifact', 'The existing project image documents the CI/CD work.'), section('Evidence boundary', 'No measured deployment-time reduction, availability target, or incident response result is provided.')] },
    change: { summary: 'A proposed pass connecting alerts to user impact and a runnable response.', sections: [section('Actionable alerts', 'Attach context, ownership, and a short investigation path to alerts. Distinguish stale telemetry from a healthy service.'), section('Deployment verification', 'Check both rollout completion and user-facing behavior, with an explicit response when either fails.')] },
  }),
  dossier({
    id: 'container-networking', sourceId: 6, title: 'Container Networking', category: 'DevOps Projects',
    skills: ['Docker Compose', 'Python', 'Ruby', 'NGINX', 'GitLab CI', 'TDD', 'REST APIs', 'Microservices'],
    summary: 'A multi-service container system explored through networking, testing, and continuous delivery.',
    demo: { summary: 'A containerized multi-service project with CI/CD and test-driven development.', media: [image('/projects/container-networking/container.png', 'Container Networking project image', 'Existing container project image.')], links: [link('Source repository', 'https://github.com/zedithx/contdevdep-ex')] },
    architecture: { summary: 'A simplified reconstruction of the recorded stack; exact routing and service topology should be read in the source repository.', diagram: [section('Ingress', 'NGINX'), section('Services', 'Python / Ruby · REST APIs'), section('Local orchestration', 'Docker Compose networking'), section('Validation and delivery', 'TDD / GitLab CI')] },
    decisions: { summary: 'The existing portfolio records service separation, container networking, and CI. These are tradeoff observations on that design.', sections: [section('Separate services', 'Service boundaries make dependencies visible but introduce network failures, timeouts, and partial availability.'), section('Test before delivery', 'TDD and CI can protect behavior as code changes. Integration and startup-order failures still need tests across the service boundary.')] },
    results: { summary: 'Recorded as a Full Marks project in the portfolio.', sections: [section('Implemented scope', 'Multi-service containers, REST APIs, CI/CD, and test-driven development.'), section('Evidence boundary', 'The academic result does not establish production throughput or availability.')], media: [image('/projects/container-networking/devopsMasterCourse.JPG', 'Container project course artifact', 'Existing course artifact.')] },
    change: { summary: 'A proposed failure-injection pass at the network and startup boundaries.', sections: [section('Partial failure', 'Stop one service, delay a response, and restart dependencies. Check timeout behavior and readiness rather than assuming every container running means the app is ready.'), section('Configuration clarity', 'Document network names, service contracts, and environment values so a new contributor can reproduce the system.')] },
  }),
  dossier({
    id: 'open-house-chatbot', sourceId: 9, title: 'Open House AI Chatbot', category: 'Student Government',
    skills: ['Python', 'Firebase', 'Telegram bots', 'AI', 'Event operations'],
    summary: 'Event information and interaction tooling for SUTD Open House.',
    demo: { summary: 'Website and backend tooling for SUTD Open House with event information and interactive features.', media: [image('/projects/openhouse2025/openhouse.png', 'Open House project image', 'Existing Open House project image.')], links: [link('Source repository', 'https://github.com/zedithx/insight-telegram-repo')] },
    architecture: { summary: 'A reconstruction from the project catalogue and repository link. The exact AI provider and deployment topology are not supplied.', diagram: [section('Visitor', 'Event information / interaction'), section('Application', 'Python backend / bot workflow'), section('Event data', 'Firebase')] },
    decisions: { summary: 'A bot and event data can bring answers closer to visitors. The rationale below is analysis of the documented project scope.', sections: [section('Answers during an event', 'A conversational entry point can be convenient. Uncertain answers and outdated schedules need a visible route to authoritative information.'), section('Shared event data', 'A maintained source of event information reduces conflicting answers across channels. Update ownership is part of the workflow.')] },
    results: { summary: 'The résumé records an AI chatbot with event pass generation for Open House registration, serving 1.8k users over two days.', sections: [section('Available evidence', 'Project image, Python/Firebase stack, linked source repository, and résumé contribution note.'), section('Evidence boundary', 'The recorded user count describes adoption. No answer-accuracy score or measured reduction in staff workload is supplied.')] },
    change: { summary: 'A proposed grounding and freshness pass for event answers.', sections: [section('Source-linked answers', 'Point responses to the current event source and make uncertain or missing information clear.'), section('Event-day fallback', 'Offer an easy route to event staff when the tool cannot answer, and rehearse schedule updates.')] },
  }),
  dossier({
    id: 'lcc-website', sourceId: 7, title: 'LCC 2025 Website', category: 'Student Government',
    skills: ['Next.js', 'Python', 'Firebase', 'Digital Ocean', 'Telegram bots', 'Event operations'],
    summary: 'Event information, Telegram voting, and lucky-draw tools for a campus learning and career event.',
    demo: { summary: 'The original project page records a Next.js event website, a Telegram voting bot, and a lucky-draw query system.', media: [image('/projects/lcc2025/lccwebsite.gif', 'LCC event website recording', 'Existing website recording.'), { type: 'video', src: '/projects/lcc2025/lcctelegrambot.mov', alt: 'LCC Telegram bot recording', caption: 'Existing Telegram bot recording; playback depends on browser codec support.' }], links: [link('Website source', 'https://github.com/zedithx/LCC_website'), link('Telegram bot source', 'https://github.com/zedithx/LCC_telebot')] },
    architecture: { summary: 'A reconstruction of the documented website and event-tool responsibilities. Catalogue dates differ in older copy, so this dossier does not infer a new delivery date.', diagram: [section('Participants', 'Website / Telegram'), section('Event tools', 'Next.js site / Python voting and draw workflow'), section('Shared records', 'Firebase'), section('Hosting', 'Digital Ocean appears in the recorded stack')] },
    decisions: { summary: 'The recorded project uses a web view and Telegram tools. This analysis considers their event-operation tradeoffs.', sections: [section('Meet participants where they are', 'A website supports browsing; a bot supports short actions such as voting. Both need a consistent view of event information and participant state.'), section('Inspectable event outcomes', 'Voting and lucky draws should make accepted actions and selection rules understandable to event organizers.')] },
    results: { summary: 'Recorded delivery of the website, voting bot, and lucky-draw query system.', sections: [section('Available evidence', 'Website GIF, bot recording, and separate linked repositories.'), section('Evidence boundary', 'No participation count, vote integrity audit, or engagement increase is supplied.')] },
    change: { summary: 'A proposed event-operation pass on repeated actions and reproducible draws.', sections: [section('Repeated requests', 'Make repeated votes or draw requests follow an explicit rule and show clear operator feedback.'), section('Event handover', 'Prepare a runbook for changing schedules, closing votes, and recording the draw result.')] },
  }),
  dossier({
    id: 'orientation-website', sourceId: 8, title: 'Orientation 2024 Website', category: 'Student Government',
    skills: ['Next.js', 'Frontend', 'Event operations'],
    summary: 'An event website that helps incoming students find orientation information.',
    demo: { summary: 'A Next.js orientation website with event information and engagement for incoming students.', media: [image('/projects/orientation2024/orientationwebsite.gif', 'Orientation website recording', 'Existing orientation website recording.')], links: [link('Source repository', 'https://github.com/zedithx/Ori_website')] },
    architecture: { summary: 'The portfolio documents a Next.js site. A backend, CMS, or hosting topology is not established in the supplied material.', diagram: [section('Incoming student', 'Browser / mobile device'), section('Event interface', 'Next.js website'), section('Content', 'Orientation information and engagement')], sections: [section('Date handling', 'Older catalogue copy uses differing event years. This reconstruction preserves the project title and does not claim a corrected date.')] },
    decisions: { summary: 'A web interface is the recorded implementation. The tradeoffs here are a present-day assessment.', sections: [section('Quick information access', 'Event visitors need schedules and locations with little navigation. Mobile clarity and content freshness affect whether the site is useful.'), section('Simple delivery', 'A focused frontend can be easy to hand over. Its information still needs an owner and a process for late changes.')] },
    results: { summary: 'The portfolio records the delivered orientation website and includes a recording.', sections: [section('Available evidence', 'Website GIF and linked source repository.'), section('Evidence boundary', 'No traffic, accessibility audit, or measured event outcome is supplied.')] },
    change: { summary: 'A proposed mobile and content-readiness pass.', sections: [section('Event-day essentials', 'Keep current location, schedule, and contact routes easy to find on a phone.'), section('Handover', 'Document how the next organizer updates content and checks links before launch.')] },
  }),
  dossier({
    id: 'night-fiesta-website', sourceId: 12, title: 'Night Fiesta 2023 Website', category: 'Student Government',
    skills: ['Next.js', 'Frontend', 'Event operations'],
    summary: 'A campus event website that presents Night Fiesta information and participant-facing content.',
    demo: { summary: 'A Next.js site for Night Fiesta, with event information and a participant experience.', media: [image('/projects/nightfiesta2023/night_fiesta.png', 'Night Fiesta website image', 'Existing Night Fiesta project image.')] },
    architecture: { summary: 'A reconstruction limited to the documented Next.js website; no undocumented backend or deployment is added.', diagram: [section('Participant', 'Browser / mobile device'), section('Website', 'Next.js'), section('Information', 'Event content and participant experience')] },
    decisions: { summary: 'The existing portfolio records a frontend event site. These observations analyze that scope.', sections: [section('Creative presentation', 'A memorable event site can support engagement. The schedule and practical information must remain readable and reachable.'), section('Event readiness', 'Asset loading and link checks matter when visitors access the site over variable connections.')] },
    results: { summary: 'Recorded delivery of the Night Fiesta website.', sections: [section('Available evidence', 'Existing website project image and recorded Next.js stack.'), section('Evidence boundary', 'No public source link, attendance effect, or traffic metric is supplied.')] },
    change: { summary: 'A proposed review of fast access and event handover.', sections: [section('Mobile access', 'Check the useful content at small widths and on slower connections, with reduced-motion preferences honored.'), section('Future organizers', 'Separate editable event information from decorative content and document the handover.')] },
  }),
  dossier({
    id: 'trading-bot', sourceId: 10, title: 'Trading Bot', category: 'Personal Projects',
    skills: ['Python', 'Cloud Storage', 'Schwab API', 'Discord', 'Telegram bots', 'Automation'],
    summary: 'A Python automation project with Discord and Telegram control around the Schwab API.',
    demo: { summary: 'An automated trading bot using the Schwab API, with Discord and Telegram interaction and control.', media: [image('/projects/tradingbot/trading_bot.png', 'Trading Bot project image', 'Existing project image. This dossier is technical project evidence, not an investment performance claim.')] },
    architecture: { summary: 'A reconstruction of the documented interfaces; no live trades or broker connection run from this portfolio.', diagram: [section('Operator', 'Discord / Telegram controls'), section('Automation', 'Python bot'), section('External interface', 'Schwab API'), section('Records', 'Cloud Storage appears in the recorded stack')] },
    decisions: { summary: 'Messaging-based control and an external API are recorded choices. These observations concern engineering behavior.', sections: [section('Convenient controls', 'Commands need clear authentication and an unambiguous accepted/rejected result.'), section('External side effects', 'An API timeout can leave execution uncertain. Retrying an operation should account for whether the first request completed.')] },
    results: { summary: 'The portfolio records the bot implementation and its messaging integrations.', sections: [section('Available evidence', 'Existing project image and Python/Cloud Storage stack.'), section('Evidence boundary', 'No return, profitability, trade volume, or risk-adjusted performance is provided or implied.')] },
    change: { summary: 'A proposed sandbox validation pass for uncertain command completion.', sections: [section('Auditability', 'Record command identity, authorization, and observed completion, with a way to reconcile uncertain responses.'), section('Dry-run mode', 'Use a dry-run or suitable sandbox workflow to test duplicate commands, expired credentials, and rate limits before enabling side effects.')] },
  }),
  dossier({
    id: '3dc-admin', sourceId: 13, title: '3DC Admin Website', category: 'Personal Projects',
    skills: ['Python', 'Django', 'Render', 'Backend', 'Administration'],
    summary: 'A Django administration site with hosted operational workflows for 3DC.',
    demo: { summary: 'An administrative website built with Django and Python, with Render recorded in the deployment stack.', media: [image('/projects/3dcadmin/3dc_logo.png', '3DC project logo', 'Existing project logo; an interface recording is not attached.')], links: [link('Source repository', 'https://github.com/zedithx/3dc_admin/tree/main/dc_admin')] },
    architecture: { summary: 'A reconstruction limited to the supplied application and hosting stack. Database choice and access-policy details are not supplied.', diagram: [section('Administrator', 'Browser'), section('Application', 'Django / Python'), section('Hosting', 'Render')] },
    decisions: { summary: 'The recorded choice uses Django for administration. These are current observations on that design.', sections: [section('Focused administrative tooling', 'A conventional framework can keep routine workflows understandable. Access scope and safe handling of changes still need attention.'), section('Hosted operations', 'Managed hosting reduces some deployment work. Configuration, backup ownership, and application-level recovery remain explicit decisions.')] },
    results: { summary: 'The portfolio records the administrative website and links its source.', sections: [section('Available evidence', 'Repository, project logo, and Django/Python/Render stack.'), section('Evidence boundary', 'No administrator count, task-time reduction, or availability measurement is supplied.')] },
    change: { summary: 'A proposed pass on safe administrative changes and recovery.', sections: [section('Change history', 'Make consequential actions inspectable and reversible where practical, with a clear confirmation of completion.'), section('Operational handover', 'Document deployment, configuration ownership, and restoration steps, then rehearse the applicable recovery flow.')] },
  }),
];

export function getProjectEvidence(id) {
  return projectEvidence.find(project => project.id === id || String(project.sourceId) === String(id)) || null;
}

export function getEvidenceFile(projectId, fileId = 'demo') {
  return getProjectEvidence(projectId)?.files.find(file => file.id === fileId) || null;
}

const normalize = value => String(value ?? '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();

export function searchProjectEvidence(query, category = 'All projects') {
  const terms = normalize(query).split(/\s+/).filter(Boolean);
  return projectEvidence.filter(project => {
    if (category !== 'All projects' && project.category !== category) return false;
    const text = normalize([project.title, project.summary, ...project.skills, ...project.tags,
      ...project.files.flatMap(file => [file.title, file.summary, ...file.sections.flatMap(entry => [entry.title, entry.body])]),
    ].join(' '));
    return terms.every(term => text.includes(term));
  });
}
